version: "3.8"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
  
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask

